[build-system]
requires = [
    "setuptools >= 40.9.0",
    "wheel",
    ]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 110

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[tool.bandit]
skips = ["B311"]

[tool.pylint.'MASTER']
#load-plugins = "pylint.extensions.docparams"

[tool.pylint.'FORMAT']
max-line-length=110
max-module-lines=2100

[tool.pylint.BASIC]
module-naming-style="PascalCase"
class-naming-style="PascalCase"
function-naming-style="PascalCase"
argument-naming-style="camelCase"
method-naming-style="camelCase"
variable-naming-style="camelCase"
attr-naming-style="camelCase"
const-naming-style="UPPER_CASE"

[tool.pylint.'MESSAGES CONTROL']
disable=["try-except-raise","broad-except","consider-using-enumerate","too-many-lines"]

[tool.pylint.messages_control]
disable = ["C0330", "C0326"]
max-line-length = 110
