
[project]
name = "lightberries"
version = "1.0.2"
dependencies = [
    "Adafruit-Blinka>=3.0.0",
    "adafruit-circuitpython-neopixel==3.4.0",
    "numpy>=2.0.0",
    "rpi_ws281x>=5.0.0",
    "RPi.GPIO>=0.7.0",
    "numpy<3.0,>=2.0",
    "pygame<3.0.0,>=2.1.2",
    "typer>=0.12.5",
    "strenum>=0.4.15",
]
requires-python = "<4.0,>=3.9"
description = "A wrapper for rpi_ws281x that does all the heavy lifting for you."
keywords = ["raspberry", "pi", "rpi", "rpi_ws281x", "adafruit", "neopixel"]
authors = [
    { name = "JoeFerg425" },
    { name = "joeferg425", email = "jokester425@gmail.com" },
    { name = "joeferg425" },
]
readme = "README.md"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/joeferg425/ws281x_lightberries"

[project.scripts]
lightberries = "__main__:main"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "black<23.0,>=22.1",
    "flake8<5.0,>=4.0",
    "matplotlib<4.0,>=3.5",
    "pytest<8.0,>=7.1",
    "mock<5.0.0,>=4.0.3",
]

[tool.pdm.build]
includes = ["src/lightberries"]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["tests/test_*.py"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "PLC0414",
    "D105",
    "S311",    # stop warning me about cryptographic security in my lights library
    "SIM108",  # I'll use a ternary operator if I want to
]
